[{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' expected.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 11,
	"endLineNumber": 1,
	"endColumn": 15,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'html' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 2,
	"endLineNumber": 2,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'head' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 2,
	"endLineNumber": 3,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 4,
	"endLineNumber": 4,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 4,
	"endLineNumber": 5,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 4,
	"endLineNumber": 6,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 7,
	"startColumn": 4,
	"endLineNumber": 7,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 4,
	"endLineNumber": 8,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 4,
	"endLineNumber": 9,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 4,
	"endLineNumber": 10,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 12,
	"startColumn": 4,
	"endLineNumber": 12,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 4,
	"endLineNumber": 13,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'meta' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 4,
	"endLineNumber": 14,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 4,
	"endLineNumber": 16,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 25,
	"endLineNumber": 16,
	"endColumn": 26,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 17,
	"startColumn": 4,
	"endLineNumber": 17,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 17,
	"startColumn": 65,
	"endLineNumber": 17,
	"endColumn": 66,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 4,
	"endLineNumber": 18,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 20,
	"startColumn": 5,
	"endLineNumber": 20,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 22,
	"startColumn": 4,
	"endLineNumber": 22,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 22,
	"startColumn": 22,
	"endLineNumber": 22,
	"endColumn": 23,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 24,
	"startColumn": 4,
	"endLineNumber": 24,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 24,
	"startColumn": 24,
	"endLineNumber": 24,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 30,
	"startColumn": 12,
	"endLineNumber": 30,
	"endColumn": 13,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 38,
	"startColumn": 5,
	"endLineNumber": 38,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 40,
	"startColumn": 14,
	"endLineNumber": 40,
	"endColumn": 15,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 43,
	"startColumn": 5,
	"endLineNumber": 43,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 15,
	"endLineNumber": 46,
	"endColumn": 16,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 24,
	"endLineNumber": 46,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 46,
	"startColumn": 32,
	"endLineNumber": 46,
	"endColumn": 33,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 47,
	"startColumn": 5,
	"endLineNumber": 47,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 12,
	"endLineNumber": 51,
	"endColumn": 13,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 55,
	"startColumn": 5,
	"endLineNumber": 55,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 57,
	"startColumn": 14,
	"endLineNumber": 57,
	"endColumn": 15,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 60,
	"startColumn": 5,
	"endLineNumber": 60,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 63,
	"startColumn": 23,
	"endLineNumber": 63,
	"endColumn": 24,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 63,
	"startColumn": 93,
	"endLineNumber": 63,
	"endColumn": 94,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 67,
	"startColumn": 14,
	"endLineNumber": 67,
	"endColumn": 15,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 71,
	"startColumn": 5,
	"endLineNumber": 71,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 73,
	"startColumn": 24,
	"endLineNumber": 73,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 73,
	"startColumn": 71,
	"endLineNumber": 73,
	"endColumn": 72,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 24,
	"endLineNumber": 74,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 114,
	"endLineNumber": 74,
	"endColumn": 115,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 26,
	"endLineNumber": 75,
	"endColumn": 27,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 119,
	"endLineNumber": 75,
	"endColumn": 120,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 25,
	"endLineNumber": 76,
	"endColumn": 26,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 177,
	"endLineNumber": 76,
	"endColumn": 178,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 77,
	"startColumn": 25,
	"endLineNumber": 77,
	"endColumn": 26,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 77,
	"startColumn": 161,
	"endLineNumber": 77,
	"endColumn": 162,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'link'.",
	"source": "ts",
	"startLineNumber": 79,
	"startColumn": 3,
	"endLineNumber": 79,
	"endColumn": 7,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 82,
	"startColumn": 4,
	"endLineNumber": 82,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 82,
	"startColumn": 81,
	"endLineNumber": 82,
	"endColumn": 82,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 91,
	"startColumn": 6,
	"endLineNumber": 91,
	"endColumn": 7,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 91,
	"startColumn": 45,
	"endLineNumber": 91,
	"endColumn": 46,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 93,
	"startColumn": 8,
	"endLineNumber": 93,
	"endColumn": 9,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 101,
	"startColumn": 9,
	"endLineNumber": 101,
	"endColumn": 10,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 104,
	"startColumn": 6,
	"endLineNumber": 104,
	"endColumn": 7,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 104,
	"startColumn": 22,
	"endLineNumber": 104,
	"endColumn": 23,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'img' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 116,
	"startColumn": 12,
	"endLineNumber": 116,
	"endColumn": 15,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'br' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 169,
	"startColumn": 42,
	"endLineNumber": 169,
	"endColumn": 44,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 177,
	"startColumn": 10,
	"endLineNumber": 177,
	"endColumn": 11,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 177,
	"startColumn": 29,
	"endLineNumber": 177,
	"endColumn": 30,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 179,
	"startColumn": 4,
	"endLineNumber": 179,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 179,
	"startColumn": 24,
	"endLineNumber": 179,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 180,
	"startColumn": 4,
	"endLineNumber": 180,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 180,
	"startColumn": 18,
	"endLineNumber": 180,
	"endColumn": 19,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 182,
	"startColumn": 4,
	"endLineNumber": 182,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 182,
	"startColumn": 30,
	"endLineNumber": 182,
	"endColumn": 31,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 184,
	"startColumn": 4,
	"endLineNumber": 184,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 184,
	"startColumn": 24,
	"endLineNumber": 184,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 186,
	"startColumn": 4,
	"endLineNumber": 186,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 186,
	"startColumn": 25,
	"endLineNumber": 186,
	"endColumn": 26,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 190,
	"startColumn": 4,
	"endLineNumber": 190,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 190,
	"startColumn": 60,
	"endLineNumber": 190,
	"endColumn": 61,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 191,
	"startColumn": 4,
	"endLineNumber": 191,
	"endColumn": 5,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 195,
	"startColumn": 5,
	"endLineNumber": 195,
	"endColumn": 6,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'link'.",
	"source": "ts",
	"startLineNumber": 197,
	"startColumn": 3,
	"endLineNumber": 197,
	"endColumn": 7,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/gaelb/Documents/GitHub/geoculture/functions/index.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'</' expected.",
	"source": "ts",
	"startLineNumber": 197,
	"startColumn": 8,
	"endLineNumber": 197,
	"endColumn": 8,
	"modelVersionId": 3,
	"origin": "extHost1"
}]